listen-address=127.0.0.1,10.29.242.94
bind-interfaces

no-resolv
server=8.8.8.8
server=1.1.1.1

# Failure Demonstration Scenario 2: DNS record points to a wrong IP address (10.29.242.250)
# (For normal mode, change .250 back to .94)
host-record=app.team1.test,10.29.242.250
host-record=api.team1.test,10.29.242.250

local-ttl=30

log-queries
log-facility=/tmp/dnsmasq.log
