listen-address=10.7.10.207
bind-interfaces

no-resolv
server=8.8.8.8
server=1.1.1.1

host-record=app.team1.test,10.7.10.207
host-record=api.team1.test,10.7.10.207

local-ttl=30

log-queries
log-facility=/tmp/dnsmasq.log
